### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by aslkeaxn** [jasp402/Easy-YOPmail#11]
## 🐛 **Issue Report**

**Title:** Can't npm install

**Labels:** bug

**Environment:**

* Operating system: 💻 Windows 11
* Version of NodeJS: 🌐 20.10.0
* Version of Easy-yopmail: 📦 4.0.23

<hr>

**Steps to Reproduce:**

1. ➡️ Create a new folder
2. ➡️ npm init -y
3. ➡️ npm i easy-yopmail

<hr>

🏳️ **Expected Behavior:**
> Library installed

🚩 **Actual Behavior:**
> npm ERR! errno -4058

📷 **Screenshots / Live demo link:**
> ![image](https://github.com/jasp402/Easy-YOPmail/assets/69468068/85d29e1d-b29f-4a8c-be87-4756932fd747)

🧮 **Additional Context:**
> None

<hr>

**🤔** I expected npm to successfully install the library, but instead it failed with `errno -4058`.

**Comment by SomeTroller77** [comment]
i am also facing this issue
please fix this issue ASAP

**Comment by jasp402** [comment]
I'm working on it. I've done a few updates. But all indications are that it is the Axios library that is causing problems. So I had to rewrite the whole project using only native libraries without dependencies. To avoid this inconvenience and possibly make installation and execution faster.

NOTE: If Liberia is installed correctly and can be used, the message is due to a dependency. Therefore, it can be used even if this message appears.

But I will upload a new version soon and let you know.

**Comment by SomeTroller77** [comment]
I noticed that, well I just downgraded to a lower version, I think 4.0.14.
I would have loved to help you but the code is obfuscated!

**Comment by jasp402** [comment]
Fixed. Please install the version [4.3.6](https://www.npmjs.com/package/easy-yopmail/v/4.3.6#) it's LTS.
