### ISSUE TITLE
Email Should Be Lowercased When Getting Emails/Messages

### ISSUE THREAD

**Issue by StephenMP** [jasp402/Easy-YOPmail#19]
When attempting to get an email via

```typescript
const message = await easyYop.readMessage("SomeEmailAddress1234@mail34.fr", id, { format: "HTML" });
```

I am presented with the error

```shell
readMessage(): Error read message
 - readMessage(): The message has been deleted or does not exist. Try reviewing the ID
```

However, the email and message does exist. When I call:

```typescript
const inboxResponse = await easyYop.getInbox("SomeEmailAddress1234@mail34.fr");
```

I receive the expected messages:

```typescript
[{
  id: "e_ZwDjAwR3ZGpkAGHlZQNjAmR4BGVjAj==",
  from: "...",
  subject: "...",
  timestamp: "17:15",
  page: 1,
}]
```

When troubleshooting, I noticed that when I looked up the messages on YOPMail, they show the email address with all lowercase letters. So changing my initial request to

```typescript
// Notice I changed it to all lowercase
const message = await easyYop.readMessage("someemailaddress1234@mail34.fr", id, { format: "HTML" });
```

I get the email message successfully.

Thus, it's likely that when attempting to get messages, the email address should be converted to lowercase prior to querying YOPMail.

**Comment by jasp402** [comment]
Good observation, I'll be checking it out. 👍🏻

**Comment by StephenMP** [comment]
It would be good to note also that it doesn't always fail to retrieve messages. Sometimes when the casing isn't all lowercase, it will still get the message, but not all the time; however, when I lowercase the email address I always get the message.

**Comment by jasp402** [comment]
I have carefully reviewed this case. The page asks you to use a custom email. You can write it, CamelCase or directly all in CAPS. However, when we go to the inbox, it is shown all in lowercase.

![image](https://github.com/user-attachments/assets/1ab9d918-2947-4478-a437-aa97e137508f)
![image](https://github.com/user-attachments/assets/383870d3-5864-4483-9d0a-798412d942c5)

The EasyYOPmail API does the same. All the text it receives is converted to lowercase.
```javascript
const easyYopmail = require('easy-yopmail');

const AUTOMATION_EMAIL = 'SomeEmailAddress1234';

easyYopmail.getInbox(AUTOMATION_EMAIL).then(emails => {
    console.log(emails);
});
``` 
![image](https://github.com/user-attachments/assets/29b1f21d-9cb7-4325-8f42-8a524c48d2c6)

It seems to me that the error you have experienced may be due to another cause.
