### ISSUE TITLE
easyYOPmail.readMail is not a function

### ISSUE THREAD

**Issue by timolarra** [jasp402/Easy-YOPmail#5]
Hi,

I am getting this error easyYOPmail.readMail is not a function, none of them is working

**Comment by jasp402** [comment]
If you are correct. 
That problem is because in version 4, the **readMail()** function was changed to **readMessage()**.
Try to test as specified in the image.
![image](https://github.com/jasp402/Easy-YOPmail/assets/8978470/254093c7-c1c6-4a84-ba9b-623c5ff2dda7)
Soon I will be updating the documentation
I'm going to close this issue. if the problem persists you can open it again.
