### ISSUE TITLE
Error: AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by m0nsieurR** [jasp402/Easy-YOPmail#6]
Hey ! When i try to getInbox of mail i have a axios error ^^
```
const easyYOPmail = require('easy-yopmail');
(async () => {
    let email = await easyYOPmail.getMail()
    let mail = await easyYOPmail.getInbox("test@yopmail.com")
    console.log(mail)
})();```

**Comment by jasp402** [comment]
I have reviewed your code. in
[https://npm.runkit.com/easy-yopmail](https://npm.runkit.com/easy-yopmail)
and it seems to work correctly if you use the most recent version. v4.0.12.

![image](https://github.com/jasp402/Easy-YOPmail/assets/8978470/ae2ea840-bcd4-4f6d-baaa-65be26fff043)

💡Suggestions:
- Check that you are using the most recent version.
- Validate if you do not have some type of block to enter Yopmail
- Enter the mail from YOPMail to verify that it is not requesting captcha.

I'm going to close this issue. if the problem persists you can open it again.

**Comment by m0nsieurR** [comment]
Hello! I updated and it didn't change anything, I manually went to Yopmail and I wasn't blocked, and I checked if I had been blocked by a captcha and that wasn't the case either.
<img width="810" alt="image" src="https://github.com/jasp402/Easy-YOPmail/assets/117940236/a5f9423f-be96-4ca8-89db-7f8e2b8171a3">
<img width="1279" alt="image" src="https://github.com/jasp402/Easy-YOPmail/assets/117940236/803f8766-bc9f-4d01-a895-ed7a79cd5305">
<img width="1281" alt="image" src="https://github.com/jasp402/Easy-YOPmail/assets/117940236/748d126c-90b8-47b2-9e71-b20b1965be69">

**Comment by jasp402** [comment]
Looking at the image you shared, I realized that you are not using the Spanish (/ES/) version of YOPMail. And that led me to review the code.
![image](https://github.com/jasp402/Easy-YOPmail/assets/8978470/886cba4a-170f-4cea-8431-65eae0155eb0)
Indeed it was assigned as a fixed value in the url and although it doesn't seem like this it affects the httprequests since the origin of the request is different.

- I have corrected the location issue. 
- I've also added more detail to the error handler to track where errors occur.
- I have tried with https://npm.runkit.com/easy-yopmail and previously it failed to read the emails, it is now working. which is a good indicator for me.

NOTE: the version with the corrections of **[4.0.16](https://www.npmjs.com/package/easy-yopmail/v/4.0.16)**
If the problem persists try to provide more details.
but i hope it works for you!
